export { h } from './h'
export { renderSlots } from './helpers/renderSlots'
export { createTextVNode } from './vNode'
export { getCurrentInstance } from './component'
export { provider, inject } from './apiInject'
export { createRenderer } from './renderer'
export type { ComponentOptions } from './createApp'
export type { RendererOptions } from './renderer'
